export const ADD_START_POINT = "ADD_START_PATH";
export const ADD_FINISH_POINT = "ADD_FINISH_POINT";
export const ADD_SHORTEST_PATH = "ADD_SHORTEST_PATH";
export const ADD_TOTAL_WEIGTH = "ADD_TOTAL_WEICHT";